# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bbox',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='confidence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
