# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20251214_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('plot_urls', models.TextField(help_text='Comma-separated URLs')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
