# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_analysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='people_data',
            field=models.TextField(default='[]', help_text='JSON list of person groups'),
        ),
    ]
